# Generated by Django 3.0.8 on 2021-04-14 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accountant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Checked', 'Checked'), ('Approved', 'Approved'), ('Invoiced', 'Invoiced')], default='Draft', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_employee', models.BooleanField(default=False)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('is_executive', models.BooleanField(default=False)),
                ('approved_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bill_approved_employee', to=settings.AUTH_USER_MODEL)),
                ('approved_executive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bill_approved_executive', to=settings.AUTH_USER_MODEL)),
                ('approved_supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bill_approved_supervisor', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bill_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254, unique=True)),
                ('customer_contact_no', models.BigIntegerField(unique=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('contact', models.BigIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Checked', 'Checked'), ('Approved', 'Approved'), ('Invoiced', 'Invoiced'), ('Billed', 'Billed')], default='Draft', max_length=50)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('is_executive', models.BooleanField(default=False)),
                ('approved_executive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_approved_executive', to=settings.AUTH_USER_MODEL)),
                ('approved_supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_approved_supervisor', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_created_by', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_vendor', to='Purchases.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price', models.CharField(max_length=100)),
                ('item_unit', models.CharField(max_length=100)),
                ('item_quantity', models.CharField(max_length=100)),
                ('item_discount', models.CharField(max_length=100)),
                ('item_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_item', to='Products.Product')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_item', to='Purchases.PurchaseOrder')),
            ],
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField()),
                ('payment_made', models.CharField(blank=True, max_length=200, null=True)),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_payment', to='Purchases.Bill')),
                ('payment_through', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_account', to='Accountant.CreateAccount')),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price', models.CharField(max_length=100)),
                ('item_unit', models.CharField(max_length=100)),
                ('item_quantity', models.CharField(max_length=100)),
                ('item_discount', models.CharField(max_length=100)),
                ('item_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bill_item', to='Purchases.Bill')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_customer', to='Purchases.Customer')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bill_item_name', to='Products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_vendor', to='Purchases.Vendor'),
        ),
    ]
