# Generated by Django 3.0.8 on 2021-04-14 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accountant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('People', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('particular', models.TextField(blank=True)),
                ('expense_image', models.ImageField(blank=True, null=True, upload_to='expense_image/')),
                ('is_supervisor', models.BooleanField(default=False)),
                ('is_accounts_first', models.BooleanField(default=False)),
                ('is_accounts_second', models.BooleanField(default=False)),
                ('is_executive', models.BooleanField(default=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=12)),
                ('approved_accounts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_accounts', to=settings.AUTH_USER_MODEL)),
                ('approved_executive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_executive', to=settings.AUTH_USER_MODEL)),
                ('approved_supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_supervisor', to=settings.AUTH_USER_MODEL)),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_account', to='Accountant.CreateAccount')),
                ('paid_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_account', to='Accountant.CreateAccount')),
                ('people_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_people_by', to='People.People')),
                ('people_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_people_for', to='People.People')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expense_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
