# Generated by Django 3.0.8 on 2020-11-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0003_auto_20201119_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='is_accounts',
            new_name='is_accounts_first',
        ),
        migrations.AddField(
            model_name='expense',
            name='is_accounts_second',
            field=models.BooleanField(default=False),
        ),
    ]
