# Generated by Django 3.0.8 on 2020-09-16 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_account', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManualJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.BigIntegerField(max_length=254, unique=True)),
                ('voucher_date', models.DateField()),
                ('account', models.CharField(max_length=254)),
                ('people_for_from', models.CharField(max_length=254)),
                ('people_by', models.CharField(max_length=254)),
                ('particular', models.TextField(blank=True)),
                ('debit', models.BigIntegerField(blank=True)),
                ('credit', models.BigIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100, unique=True)),
                ('account_code', models.IntegerField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createaccount_account_type', to='Accountant.AccountType')),
            ],
        ),
        migrations.AddField(
            model_name='accounttype',
            name='base_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounttype_baseaccount', to='Accountant.BaseAccount'),
        ),
    ]
