# Generated by Django 3.0.8 on 2020-09-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualjournal',
            name='image',
            field=models.ImageField(blank=True, upload_to='journal_image/'),
        ),
        migrations.AddField(
            model_name='manualjournal',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='manualjournal',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='manualjournal',
            name='voucher_no',
            field=models.BigIntegerField(unique=True),
        ),
    ]
