# Generated by Django 3.0.8 on 2020-09-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accountant', '0002_auto_20200921_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualjournal',
            name='image',
        ),
    ]
