# Generated by Django 3.0.8 on 2020-09-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accountant', '0003_remove_manualjournal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualjournal',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='manualjournal',
            name='reference',
        ),
    ]
