# Generated by Django 3.0.8 on 2020-09-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountant', '0004_auto_20200921_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualjournal',
            name='credit',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='manualjournal',
            name='debit',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
