# Generated by Django 3.0.8 on 2020-09-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountant', '0007_auto_20200921_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualjournal',
            name='voucher_no',
            field=models.CharField(max_length=100),
        ),
    ]
