# Generated by Django 3.0.8 on 2020-09-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountant', '0008_auto_20200922_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualjournal',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='manualjournal',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
