# Generated by Django 3.0.8 on 2020-09-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0020_auto_20200921_1451'),
        ('Accountant', '0010_auto_20200924_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualjournal',
            name='account',
        ),
        migrations.AddField(
            model_name='manualjournal',
            name='accounts',
            field=models.ManyToManyField(related_name='account', to='Accountant.CreateAccount'),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='credit',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='debit',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.RemoveField(
            model_name='manualjournal',
            name='people_by',
        ),
        migrations.AddField(
            model_name='manualjournal',
            name='people_by',
            field=models.ManyToManyField(related_name='people_by', to='People.People'),
        ),
        migrations.RemoveField(
            model_name='manualjournal',
            name='people_for_from',
        ),
        migrations.AddField(
            model_name='manualjournal',
            name='people_for_from',
            field=models.ManyToManyField(related_name='people_for', to='People.People'),
        ),
    ]
