# Generated by Django 3.0.8 on 2020-09-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountant', '0012_auto_20200924_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createaccount',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='debit',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='manualjournal',
            name='account',
        ),
        migrations.AddField(
            model_name='manualjournal',
            name='account',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.RemoveField(
            model_name='manualjournal',
            name='people_by',
        ),
        migrations.AddField(
            model_name='manualjournal',
            name='people_by',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.RemoveField(
            model_name='manualjournal',
            name='people_for_from',
        ),
        migrations.AddField(
            model_name='manualjournal',
            name='people_for_from',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
