# Generated by Django 3.0.8 on 2020-09-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountant', '0015_auto_20200927_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualjournal',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='manualjournal',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
