# Generated by Django 3.0.8 on 2020-10-05 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accountant', '0018_auto_20200927_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trnsaction_type', models.CharField(blank=True, max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('total_debit', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('total_credit', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_account', to='Accountant.CreateAccount')),
            ],
        ),
    ]
