# Generated by Django 3.0.8 on 2020-10-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accountant', '0019_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createaccount',
            name='total_credit',
        ),
        migrations.RemoveField(
            model_name='createaccount',
            name='total_debit',
        ),
    ]
