# Generated by Django 3.0.8 on 2020-10-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountant', '0020_auto_20201005_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='createaccount',
            name='total_credit',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
        migrations.AddField(
            model_name='createaccount',
            name='total_debit',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
    ]
