# Generated by Django 3.0.8 on 2020-08-13 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact', models.IntegerField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='people_images')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], default='Select', max_length=50, null=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], default='Select', max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('nid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('passport', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tracking', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_company', to='People.Company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people_department', to='People.Department')),
            ],
        ),
    ]
