# Generated by Django 3.0.8 on 2020-08-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0006_auto_20200813_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
