# Generated by Django 3.0.8 on 2020-08-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0008_auto_20200813_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='people_image/'),
        ),
    ]
