# Generated by Django 3.0.8 on 2020-08-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0009_auto_20200816_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='people_image/'),
        ),
    ]
