# Generated by Django 3.0.8 on 2020-08-16 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0011_auto_20200816_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='image',
        ),
    ]
