# Generated by Django 3.0.8 on 2020-08-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0013_auto_20200816_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], default='Select', max_length=50, null=True),
        ),
    ]
