# Generated by Django 3.0.8 on 2020-08-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0014_auto_20200816_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='passport',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='tracking',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
