# Generated by Django 3.0.8 on 2020-08-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0015_auto_20200816_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=50, null=True),
        ),
    ]
