# Generated by Django 3.0.8 on 2020-08-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0016_auto_20200816_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='contact',
            field=models.IntegerField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='nid',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
