# Generated by Django 3.0.8 on 2020-08-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0018_auto_20200817_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=100),
        ),
    ]
