# Generated by Django 3.0.8 on 2020-10-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0020_auto_20200921_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='contact',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='nid',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
