# Generated by Django 3.0.8 on 2020-10-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0021_auto_20201025_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='nid',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='tracking',
            field=models.CharField(blank=True, max_length=254, unique=True),
        ),
    ]
