# Generated by Django 3.0.8 on 2020-11-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0024_auto_20201027_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('', '--Select--'), ('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('', '--Select--'), ('Single', 'Single'), ('Married', 'Married')], max_length=50, null=True),
        ),
    ]
