# Generated by Django 3.0.8 on 2021-04-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_no',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
