# Generated by Django 3.0.8 on 2021-04-14 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accountant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('Goods', 'Goods'), ('Fish', 'Fish'), ('Others', 'Others')], max_length=100)),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('unit', models.CharField(choices=[('Liter', 'Liter'), ('Box', 'Box'), ('Pcs', 'Pcs'), ('cm', 'cm'), ('dz', 'dz'), ('ft', 'ft'), ('g', 'g'), ('in', 'in'), ('kg', 'kg'), ('km', 'km'), ('lb', 'lb'), ('mg', 'mg'), ('m', 'm')], max_length=100)),
                ('selling_price', models.FloatField(blank=True, null=True)),
                ('selling_description', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_price', models.FloatField(blank=True, null=True)),
                ('cost_description', models.CharField(blank=True, max_length=250, null=True)),
                ('track_inventory', models.BooleanField(default=False)),
                ('cost_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_account', to='Accountant.CreateAccount')),
                ('selling_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selling_account', to='Accountant.CreateAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_stock', models.FloatField(blank=True, null=True)),
                ('opening_stock_rate_per_unit', models.FloatField(blank=True, null=True)),
                ('inventory_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_account', to='Accountant.CreateAccount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inventory', to='Products.Product')),
            ],
        ),
    ]
